import {ubuntu,kali,mint,parrot,pop,arch_linux}  from '../assets'
import {go,c,cplus,chas,ruby,rust,node,} from "../assets/Programming_lang"


const cards = [
    {
        main_img:ubuntu,
        name:"ubuntu",
        subname:"Terminal",
        description:"Ubuntu is a Linux distribution derived from Debian and composed mostly of free and open-source software. Ubuntu is officially released in multiple editions: Desktop, Server, and Core for Internet of things devices and robots.",
        image:[
            {
                img_name:"go",
                img:go
            },
            {
                img_name:"ruby",
                img:ruby
            },
            {
                img_name:"rust",
                img:rust
            },
            {
                img_name:"node",
                img:node
            }
        ]
    },
    {
        main_img:kali,
        name:"kali_linux",
        subname:"Terminal",
        description:"Ubuntu is a Linux distribution derived from Debian and composed mostly of free and open-source software. Ubuntu is officially released in multiple editions: Desktop, Server, and Core for Internet of things devices and robots.",
        image:[
            {
                img_name:"go",
                img:go
            },
            {
                img_name:"kali",
                img:c
            },
            {
                img_name:"kali",
                img:chas
            },
            {
                img_name:"kali",
                img:cplus
            }
        ]
    },
    {
        main_img:mint,
        name:"mint",
        subname:"Terminal",
        description:"Ubuntu is a Linux distribution derived from Debian and composed mostly of free and open-source software. Ubuntu is officially released in multiple editions: Desktop, Server, and Core for Internet of things devices and robots.",
        image:[
            {
                img_name:"go",
                img:go
            },
            {
                img_name:"kali",
                img:c
            },
            {
                img_name:"kali",
                img:chas
            },
            {
                img_name:"kali",
                img:cplus
            }
        ]
    },
    {
        main_img:parrot,
        name:"parrot",
        subname:"Terminal",
        description:"Ubuntu is a Linux distribution derived from Debian and composed mostly of free and open-source software. Ubuntu is officially released in multiple editions: Desktop, Server, and Core for Internet of things devices and robots.",
        image:[
            {
                img_name:"go",
                img:go
            },
            {
                img_name:"kali",
                img:c
            },
            {
                img_name:"kali",
                img:chas
            },
            {
                img_name:"kali",
                img:cplus
            }
        ]
    },
    {
        main_img:arch_linux,
        name:"arch_linux",
        subname:"Terminal",
        description:"Ubuntu is a Linux distribution derived from Debian and composed mostly of free and open-source software. Ubuntu is officially released in multiple editions: Desktop, Server, and Core for Internet of things devices and robots.",
        image:[
            {
                img_name:"go",
                img:go
            },
            {
                img_name:"kali",
                img:c
            },
            {
                img_name:"kali",
                img:chas
            },
            {
                img_name:"kali",
                img:cplus
            }
        ]
    },
    {
        main_img:pop,
        name:"pop",
        subname:"Terminal",
        description:"Ubuntu is a Linux distribution derived from Debian and composed mostly of free and open-source software. Ubuntu is officially released in multiple editions: Desktop, Server, and Core for Internet of things devices and robots.",
        image:[
            {
                img_name:"go",
                img:go
            },
            {
                img_name:"kali",
                img:c
            },
            {
                img_name:"kali",
                img:chas
            },
            {
                img_name:"kali",
                img:cplus
            }
        ]
    },
]

export {cards}
